/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/ui/alert/Alert.vue')['default']
    AlertDescription: typeof import('./src/components/ui/alert/AlertDescription.vue')['default']
    AlertTitle: typeof import('./src/components/ui/alert/AlertTitle.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardAction: typeof import('./src/components/ui/card/CardAction.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/ui/skeleton/Skeleton.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs/TabsTrigger.vue')['default']
    TheButton: typeof import('./src/components/ui/button/TheButton.vue')['default']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheInput: typeof import('./src/components/ui/input/TheInput.vue')['default']
    TheLoader: typeof import('./src/components/TheLoader.vue')['default']
    TheLogo: typeof import('./src/components/TheLogo.vue')['default']
    TheSkeleton: typeof import('./src/components/ui/skeleton/TheSkeleton.vue')['default']
    TheSonner: typeof import('./src/components/ui/sonner/TheSonner.vue')['default']
  }
}
